# Autograd - Build
This is the build section of the project, where new functions, classes, etc are created and tested. Finished peices are moved into main where they are then called and used by build.

### Rules:
- No ai used to generate any code, only for reaserch, explinations and code reviews
- Finished peices must be abstract and state clearly if any cases are not covered

## Setup

In [ ]:
import numpy as np
import main
from typing import Union, List
from matplotlib import pyplot as plt
import matplotlib_inline
%matplotlib

## Build

In [ ]:
class Model():
    """
    
    """
    def __init__(self,
                  input_size : int, hidden_size : int, output_size : int,
                  number_of_layers : int, activation_function, normalisation_function,
                  precision: str = 'float32', random_seed: int = None):
        
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.number_of_layers = number_of_layers

        self.precision = precision
        self.random_seed = random_seed

        self.activation_function = activation_function
        self.normalisation_function = normalisation_function

        self.activation_function_derivative = main.derivatives.get(
            getattr(self.activation_function, "__name__", None)
        )
        self.normalisation_function_derivative = main.derivatives.get(
            getattr(self.normalisation_function, "__name__", None)
        )


        layers = []
        if self.number_of_layers == 1:
            layers.append(main.LinearLayer(self.input_size, self.output_size,
                                             self.precision, self.random_seed))
        else:
            layers.append(
                main.LinearLayer(self.input_size, self.hidden_size, self.precision, self.random_seed))
            for _ in range(max(0, self.number_of_layers - 2)):
                layers.append(self.activation_function)
                layers.append(main.LinearLayer(self.hidden_size, self.hidden_size, 
                                               self.precision, self.random_seed))
            layers.append(main.LinearLayer(self.hidden_size, self.output_size, 
                                           self.precision, self.random_seed))

        layers.append(self.activation_function)
        layers.append(self.normalisation_function)

        self.modules = layers

    def forward(self, x: Union[np.ndarray, List, float, int]) -> np.ndarray:
        for module in self.modules:
            if hasattr(module, "forward") and callable(module.forward):
                x = module.forward(x)
            elif callable(module):
                x = module(x)
            else:
                raise TypeError(f"Module - {type(module).__name__} does not have a 'forward' function, or is not callable and so is not supported")
            print(x)
        return x

    

In [ ]:
test_inputs = [
    np.array([-1, -0.5, 0]),
    [[0, 1, 2], [2, 0.7, -1]],
    (-2, -0.32, 0),
    "This is a string."
]

model = Model(input_size=3, output_size=2, hidden_size=5,
              number_of_layers=3, activation_function=main.ReLU, normalisation_function=main.Softmax,
              random_seed=1)

In [18]:
for t in test_inputs:
    try:
        print(f"Input - {t} - Output - {model.forward(t)}")
        print()
    except:
        print(f"Input - {t} - can not be passed through the model.")

[[ 0.228      -0.05849999 -0.85950005 -1.4779999   0.17450005]]
[[0.228      0.         0.         0.         0.17450005]]
[[-0.22575246 -0.00128447  0.81006753 -0.53453803 -0.49546045]]
[[-0.10069329 -1.0298084 ]]
[[0. 0.]]
[[0.5 0.5]]
Input - [-1.  -0.5  0. ] - Output - [[0.5 0.5]]

[[ 0.58199996  0.62399995  0.08800002 -0.02100003 -2.296     ]
 [-1.5264      0.9385      2.2009     -0.03540003 -2.5839    ]]
[[0.58199996 0.62399995 0.08800002 0.         0.        ]
 [0.         0.9385     2.2009     0.         0.        ]]
[[-0.7517719   0.30731395  1.3925959  -0.484808   -1.2139459 ]
 [ 0.6150522   0.17139387  0.41862583  0.21746248 -1.8196528 ]]
[[-0.06448138 -0.86345166]
 [ 1.4561863   0.59741205]]
[[0.         0.        ]
 [1.4561863  0.59741205]]
[[0.5       0.5      ]
 [0.7024045 0.2975955]]
Input - [[0, 1, 2], [2, 0.7, -1]] - Output - [[0.5       0.5      ]
 [0.7024045 0.2975955]]

[[ 0.15383999  0.03460002 -1.20804    -2.46836     1.0376401 ]]
[[0.15383999 0.03460002 0.       