# Autograd - Build
This is the build section of the project, where new functions, classes, etc are created and tested. Finished peices are moved into main where they are then called and used by build.

### Rules:
- No ai used to generate any code, only for reaserch, explinations and code reviews
- Finished peices must be abstract and state clearly if any cases are not covered

## Setup

In [1]:
import numpy as np
import main
from typing import Union, List
import torch

## Build

In [2]:
layer = main.LinearLayer(3, 2, "float16", 0)

In [6]:
layer.forward([[1, 2, 3],[4, 5, 6]])
layer.update_parameters(0.1)

SequenceError: A backwards pass must have been compleated imidatley before updating layer paramaters.

In [5]:
two_d = np.array([[1, 2, 3], [0.8, 0.2, 0]])
two_d_ans = np.array([[0, 1], [0, 1]])

# test = np.array([2, 3])
# test_error = np.array([1, 0])

print(layer.weight_matrix, layer.bias_matrix, "\n")
print(layer.forward(two_d), "\n")
print(layer.last_inputed_array, "\n")
layer.backwards(two_d_ans)
print(layer.dW, layer.dB, layer.passed_down_grad, "\n")


[[-0.15  -0.829]
 [-0.527  0.42 ]
 [-0.943 -0.339]] [ 0.375 -0.58 ] 

[[-3.656  -1.587 ]
 [ 0.1497 -1.159 ]] 

[[1.  2.  3. ]
 [0.8 0.2 0. ]] 

[[0.  1.8]
 [0.  2.2]
 [0.  3. ]] [[0. 2.]] [[-0.829  0.42  -0.339]
 [-0.829  0.42  -0.339]] 

