# Autograd - Build
This is the build section of the project, where new functions, classes, etc are created and tested. Finished peices are moved into main where they are then called and used by build.

### Rules:
- No ai used to generate any code, only for reaserch, explinations and code reviews
- Finished peices must be abstract and state clearly if any cases are not covered

## Setup

In [12]:
import numpy as np
# from main import

## Build

In [ ]:
def ReLu(input: np.ndarray) -> np.ndarray:
    """
    A vectorised version of ReLu
    Applies the ReLu function on a given numpy array \n
    ReLu is defined as "max(x, 0)"

    Args:
    input(array): The tensor which the function will be applied to.

    Returns:
    np.array: The same array inputed, with each item having had the ReLu function appied to it.
    """
    def relu(x):
        return max(x, 0)

    self = np.frompyfunc(relu, 1, 1)
    return self(input)



x = np.array([[-2, -1.5, 0, 1, 2.56],
             [0.1, 3, 1, 1, 1]])
print(x)
print(ReLu(x))

[[-2.   -1.5   0.    1.    2.56]
 [ 0.1   3.    1.    1.    1.  ]]
[[0 0 0.0 1.0 2.56]
 [0.1 3.0 1.0 1.0 1.0]]
